In [1]:
import pandas as pd

In [2]:
df_atc = pd.read_csv('../data/aware_2019_atc.csv')

In [4]:
df_atc

                             ATC name ATC code route England AWaRe
0                            AMIKACIN  J01GB06     P         Watch
1                         AMOXICILLIN  J01CA04     P        Access
2                         AMOXICILLIN  J01CA04     O        Access
3    AMOXICILLIN AND ENZYME INHIBITOR  J01CR02     O         Watch
4    AMOXICILLIN AND ENZYME INHIBITOR  J01CR02     P         Watch
..                                ...      ...   ...           ...
203                    TROLEANDOMYCIN  J01FA08     O         Watch
204                     TROVAFLOXACIN  J01MA13     O         Watch
205                     TROVAFLOXACIN  J01MA13     P         Watch
206                        VANCOMYCIN  J01XA01     P         Watch
207                        VANCOMYCIN  A07AA09     O         Watch

[208 rows x 4 columns]

In [21]:
# Set URL to scrape
url = "https://www.gov.uk/government/publications/uk-aware-antibiotic-classification/uk-access-watch-reserve-and-other-classification-for-antibiotics-uk-aware-antibiotic-classification"

# Read the first HTML table from the page into a DataFrame using the HTML content
df_new = pd.read_html(url)[0]

df_new['Antibiotic'] = df_new['Antibiotic'].str.replace(" #", "", regex=False)

route_list = ["oral", "intravenous"]
for route in route_list:
    df_new['Antibiotic'] = df_new['Antibiotic'].str.replace(fr'(, | ){route}$', '', regex=True)
    
    
name_dict = {
    "Amoxicillin/ clavulanic-acid": "AMOXICILLIN AND ENZYME INHIBITOR",
    "Benzathine-benzylpenicillin": "BENZATHINE BENZYLPENICILLIN",
    "Ceftaroline-fosamil": "CEFTAROLINE_FOSAMIL",
    "Ceftazidime/ avibactam": "CEFTAZIDIME AND BETA-LACTAMASE INHIBITOR",
    "Ceftobiprole-medocaril": "CEFTOBIPROLE",
    "Fusidic acid": "FUSIDIC_ACID",
    "Piperacillin/tazobactam": "PIPERACILLIN AND ENZYME INHIBITOR",
    "Procaine-benzylpenicillin": "PROCAINE BENZYLPENICILLIN",
    "Sulfamethoxazole/ trimethoprim": "CO-TRIMOXAZOLE"
}
df_new['Antibiotic'] = df_new['Antibiotic'].replace(name_dict)



# Display the DataFrame
df_new

,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
0,Amikacin,Watch,Watch
1,Amoxicillin,Access,Access
2,AMOXICILLIN AND ENZYME INHIBITOR,Watch,Watch
3,Ampicillin,Access,Access
4,Azithromycin,Watch,Watch
...,...,...,...
85,Tigecycline,Reserve,Reserve
86,Tinidazole,Other,Access
87,Tobramycin,Watch,Watch
88,Trimethoprim,Access,Access
89,Vancomycin,Watch,Watch

In [22]:
# Create temporary lowercase columns for case-insensitive join
df_atc['atc_lower'] = df_atc['ATC name'].str.lower()
df_new['antibiotic_lower'] = df_new['Antibiotic'].str.lower()

# Perform the inner join on the temporary columns
df_joined = df_atc.merge(df_new, left_on='atc_lower', right_on='antibiotic_lower', how='outer')

# Optionally, drop the helper columns
df_joined = df_joined.drop(columns=['atc_lower', 'antibiotic_lower'])

In [23]:
df_joined

,ATC name,ATC code,route,England AWaRe,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
0,AMIKACIN,J01GB06,P,Watch,Amikacin,Watch,Watch
1,AMOXICILLIN,J01CA04,P,Access,Amoxicillin,Access,Access
2,AMOXICILLIN,J01CA04,O,Access,Amoxicillin,Access,Access
3,AMOXICILLIN AND ENZYME INHIBITOR,J01CR02,O,Watch,AMOXICILLIN AND ENZYME INHIBITOR,Watch,Watch
4,AMOXICILLIN AND ENZYME INHIBITOR,J01CR02,P,Watch,AMOXICILLIN AND ENZYME INHIBITOR,Watch,Watch
...,...,...,...,...,...,...,...
220,NaN,NaN,NaN,NaN,Imipenem/cilastatin,Reserve,Reserve
221,NaN,NaN,NaN,NaN,Imipenem/cilastatin/relebactam,Reserve,Reserve
222,NaN,NaN,NaN,NaN,Meropenem/ vaborbactam,Reserve,Reserve
223,NaN,NaN,NaN,NaN,Methenamine,Other,Other
224,NaN,NaN,NaN,NaN,Nalidixic Acid,Other,Other

In [24]:
df_joined[df_joined.isnull().any(axis=1)]

,ATC name,ATC code,route,England AWaRe,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
7,AMPICILLIN COMBINATIONS,J01CA51,P,Access,NaN,NaN,NaN
12,BEDAQUILINE,J04AK05,O,Other,NaN,NaN,NaN
15,BIAPENEM,J01DH05,P,Watch,NaN,NaN,NaN
16,CAPREOMYCIN,J04AB30,P,Other,NaN,NaN,NaN
17,CARUMONAM,J01DF02,P,Other,NaN,NaN,NaN
...,...,...,...,...,...,...,...
220,NaN,NaN,NaN,NaN,Imipenem/cilastatin,Reserve,Reserve
221,NaN,NaN,NaN,NaN,Imipenem/cilastatin/relebactam,Reserve,Reserve
222,NaN,NaN,NaN,NaN,Meropenem/ vaborbactam,Reserve,Reserve
223,NaN,NaN,NaN,NaN,Methenamine,Other,Other
224,NaN,NaN,NaN,NaN,Nalidixic Acid,Other,Other

In [25]:
with pd.option_context('display.max_rows', None):
    display(df_joined[df_joined.isnull().any(axis=1)])

,ATC name,ATC code,route,England AWaRe,Antibiotic,England-adapted 2019 AWaRe category,UK-adapted 2024 AWaRe category
7,AMPICILLIN COMBINATIONS,J01CA51,P,Access,NaN,NaN,NaN
12,BEDAQUILINE,J04AK05,O,Other,NaN,NaN,NaN
15,BIAPENEM,J01DH05,P,Watch,NaN,NaN,NaN
16,CAPREOMYCIN,J04AB30,P,Other,NaN,NaN,NaN
17,CARUMONAM,J01DF02,P,Other,NaN,NaN,NaN
23,CEFCAPENE,J01DD17,O,Watch,NaN,NaN,NaN
24,CEFDINIR,J01DD15,O,Watch,NaN,NaN,NaN
25,CEFDITOREN,J01DD16,O,Watch,NaN,NaN,NaN
27,CEFETAMET,J01DD10,O,Watch,NaN,NaN,NaN
29,CEFMENOXIME,J01DD05,P,Watch,NaN,NaN,NaN
30,CEFODIZIME,J01DD09,P,Watch,NaN,NaN,NaN
31,CEFOPERAZONE,J01DD12,P,Watch,NaN,NaN,NaN
32,CEFOPERAZONE AND ENZYME INHIBITOR,J01DD62,P,Watch,NaN,NaN,NaN
34,CEFOTAXIME AND ENZYME INHIBITOR,J01DD51,P,Watch,NaN,NaN,NaN
36,CEFOZOPRAN,J01DE03,P,Reserve,NaN,NaN,NaN
37,CEFPIRAMIDE,J01DD11,P,Watch,NaN,NaN,NaN
38,CEFPIROME,J01DE02,P,Reserve,NaN,NaN,NaN
39,CEFPODOXIME,J01DD13,O,Watch,NaN,NaN,NaN
40,CEFPROZIL,J01DC10,O,Watch,NaN,NaN,NaN
43,CEFSULODIN,J01DD03,P,Watch,NaN,NaN,NaN
47,CEFTIBUTEN,J01DD14,O,Watch,NaN,NaN,NaN
48,CEFTIZOXIME,J01DD07,P,Watch,NaN,NaN,NaN
50,CEFTOLOZANE,J01DI54,P,Reserve,NaN,NaN,NaN
52,CEFTRIAXONE AND ENZYME INHIBITOR,J01DD63,P,Watch,NaN,NaN,NaN
53,CEFTRIAXONE COMBINATIONS,J01DD54,P,Watch,NaN,NaN,NaN
58,CINOXACIN,J01MB06,O,Watch,NaN,NaN,NaN
65,CLOFAZIMINE,J04BA01,O,Other,NaN,NaN,NaN
66,CLOXACILLIN,J01CF02,O,Access,NaN,NaN,NaN
67,CLOXACILLIN,J01CF02,P,Access,NaN,NaN,NaN
68,CO-FLUAMPICIL,J01CR50,P,Other,NaN,NaN,NaN
69,CO-FLUAMPICIL,J01CR50,O,Other,NaN,NaN,NaN
80,CYCLOSERINE,J04AB01,O,Other,NaN,NaN,NaN
83,DELAMANID,J04AK06,O,Other,NaN,NaN,NaN
85,DICLOXACILLIN,J01CF01,O,Other,NaN,NaN,NaN
86,DICLOXACILLIN,J01CF01,P,Other,NaN,NaN,NaN
87,DIRITHROMYCIN,J01FA13,O,Watch,NaN,NaN,NaN
92,ENOXACIN,J01MA04,O,Watch,NaN,NaN,NaN
96,ERYTHROMYCIN ETHYLSUCCINATE,J01FA01,O,Watch,NaN,NaN,NaN
97,ETHAMBUTOL,J04AK02,O,Other,NaN,NaN,NaN
98,ETHAMBUTOL,J04AK02,P,Other,NaN,NaN,NaN
99,FAROPENEM,J01DI03,O,Watch,NaN,NaN,NaN
101,FLEROXACIN,J01MA08,O,Watch,NaN,NaN,NaN
102,FLEROXACIN,J01MA08,P,Watch,NaN,NaN,NaN
105,FLUMEQUINE,J01MB07,O,Watch,NaN,NaN,NaN
106,FLURITHROMYCIN,J01FA14,O,Watch,NaN,NaN,NaN
112,GARENOXACIN,J01MA19,O,Watch,NaN,NaN,NaN
113,GATIFLOXACIN,J01MA16,O,Watch,NaN,NaN,NaN
114,GATIFLOXACIN,J01MA16,P,Watch,NaN,NaN,NaN
115,GEMIFLOXACIN,J01MA15,O,Watch,NaN,NaN,NaN
116,GENERIC_DETECLO,J01AA01,O,Other,NaN,NaN,NaN
117,GENERIC_RIFATER,J04AM05,O,Other,NaN,NaN,NaN
119,GREPAFLOXACIN,J01MA11,O,Watch,NaN,NaN,NaN
120,IMIPENEM,J01DH51,P,Reserve,NaN,NaN,NaN
121,ISONIAZID,J04AC01,O,Other,NaN,NaN,NaN
122,ISONIAZID,J04AC01,P,Other,NaN,NaN,NaN
123,JOSAMYCIN,J01FA07,O,Watch,NaN,NaN,NaN
124,LATAMOXEF,J01DD06,P,Watch,NaN,NaN,NaN
129,LOMEFLOXACIN,J01MA07,O,Watch,NaN,NaN,NaN
132,METHENAMINE_HIPPURATE,J01XX05,O,Other,NaN,NaN,NaN
133,METICILLIN,J01CF03,P,Other,NaN,NaN,NaN
138,MIDECAMYCIN,J01FA03,P,Watch,NaN,NaN,NaN
140,MIOCAMYCIN,J01FA11,O,Watch,NaN,NaN,NaN
143,NAFCILLIN,J01CF06,P,Other,NaN,NaN,NaN
144,NALIDIXIC_ACID,J01MB02,O,Watch,NaN,NaN,NaN
146,NETILMICIN,J01GB07,O,Other,NaN,NaN,NaN
151,OLEANDOMYCIN,J01FA05,O,Watch,NaN,NaN,NaN
153,OXACILLIN,J01CF04,O,Other,NaN,NaN,NaN
154,OXACILLIN,J01CF04,P,Other,NaN,NaN,NaN
155,OXOLINIC ACID,J01MB05,O,Watch,NaN,NaN,NaN
157,PANIPENEM,J01DH55,P,Watch,NaN,NaN,NaN
158,PAZUFLOXACIN,J01MA18,P,Watch,NaN,NaN,NaN
159,PELFLOXACIN,J01MA03,O,Watch,NaN,NaN,NaN
160,PELFLOXACIN,J01MA03,P,Watch,NaN,NaN,NaN
162,PIPEMIDIC ACID,J01MB04,O,Watch,NaN,NaN,NaN
165,PIROMIDIC ACID,J01MB03,O,Watch,NaN,NaN,NaN
167,POLYMIXIN B,J01XB02,P,Reserve,NaN,NaN,NaN
168,POLYMIXIN B,A07AA05,O,Reserve,NaN,NaN,NaN
171,PRULIFLOXACIN,J01MA17,O,Watch,NaN,NaN,NaN
172,PYRAZINAMIDE,J04AK01,O,Other,NaN,NaN,NaN
173,QUINUPRISTIN,J01FG02,P,Watch,NaN,NaN,NaN
174,RIFAMPICIN,J04AB02,P,Other,NaN,NaN,NaN
175,RIFAMPICIN,J04AB02,O,Other,NaN,NaN,NaN
176,ROKITAMYCIN,J01FA12,O,Watch,NaN,NaN,NaN
177,ROSOXACIN,J01MB01,O,Watch,NaN,NaN,NaN
178,ROXITHROMYCIN,J01FA06,O,Watch,NaN,NaN,NaN
179,RUFLOXACIN,J01MA10,O,Watch,NaN,NaN,NaN
180,SITAFLOXACIN,J01MA21,O,Watch,NaN,NaN,NaN
181,SODIUM_FUSIDATE,J01XC01,P,Access,NaN,NaN,NaN
182,SODIUM_FUSIDATE,J01XC01,O,Access,NaN,NaN,NaN
183,SOLITHROMYCIN,J01FA16,O,Watch,NaN,NaN,NaN
184,SPARFLOXACIN,J01MA09,O,Watch,NaN,NaN,NaN
191,SULFASALAZINE,A07EC01,R,Other,NaN,NaN,NaN
196,TELITHROMYCIN,J01FA15,O,Watch,NaN,NaN,NaN
197,TEMAFLOXACIN,J01MA05,O,Watch,NaN,NaN,NaN
200,TETRACYCLINE COMBINATIONS,J01AA20,O,Watch,NaN,NaN,NaN
201,TICARCILLIN,J01CA13,P,Watch,NaN,NaN,NaN
202,TICARCILLIN AND ENZYME INHIBITOR,J01CR03,P,Watch,NaN,NaN,NaN
209,TROLEANDOMYCIN,J01FA08,O,Watch,NaN,NaN,NaN
210,TROVAFLOXACIN,J01MA13,O,Watch,NaN,NaN,NaN
211,TROVAFLOXACIN,J01MA13,P,Watch,NaN,NaN,NaN
214,NaN,NaN,NaN,NaN,Cefalotin,Watch,Access
215,NaN,NaN,NaN,NaN,Cefiderocol,Reserve,Reserve
216,NaN,NaN,NaN,NaN,Ceftolozane/ tazobactam,Reserve,Reserve
217,NaN,NaN,NaN,NaN,Dalfopristin/ quinupristin,Reserve,Reserve
218,NaN,NaN,NaN,NaN,Delafloxacin,Watch,Watch
219,NaN,NaN,NaN,NaN,Eravacycline,Reserve,Reserve
220,NaN,NaN,NaN,NaN,Imipenem/cilastatin,Reserve,Reserve
221,NaN,NaN,NaN,NaN,Imipenem/cilastatin/relebactam,Reserve,Reserve
222,NaN,NaN,NaN,NaN,Meropenem/ vaborbactam,Reserve,Reserve
223,NaN,NaN,NaN,NaN,Methenamine,Other,Other
224,NaN,NaN,NaN,NaN,Nalidixic Acid,Other,Other

In [ ]:
Amoxicillin/ clavulanic-acid: AMOXICILLIN AND ENZYME INHIBITOR
Benzathine-benzylpenicillin: BENZATHINE BENZYLPENICILLIN
Cefalotin
Cefiderocol
Ceftaroline-fosamil: CEFTAROLINE_FOSAMIL
Ceftazidime/ avibactam: CEFTAZIDIME AND BETA-LACTAMASE INHIBITOR
Ceftobiprole-medocaril: CEFTOBIPROLE
Ceftolozane/ tazobactam	
Dalfopristin/ quinupristin	
Delafloxacin
Eravacycline
Fusidic acid: FUSIDIC_ACID
Imipenem/cilastatin
Imipenem/cilastatin/relebactam
Meropenem/ vaborbactam
Methenamine
Nalidixic Acid
Piperacillin/tazobactam: PIPERACILLIN AND ENZYME INHIBITOR
Procaine-benzylpenicillin: PROCAINE BENZYLPENICILLIN
Sulfamethoxazole/ trimethoprim: CO-TRIMOXAZOLE