## AWaRe via ATC Codes
This notebook explores an alternative mapping of AWaRe classifications via ATC codes. This is a standalone approach and not directly linked to the dm+d-based mapping used in the main notebook.

### UK Access, Watch, Reserve, and Other classification for antibiotics in dmd

The ["UK Access, Watch, Reserve, and Other classification for antibiotics"](https://www.gov.uk/government/publications/uk-aware-antibiotic-classification/uk-access-watch-reserve-and-other-classification-for-antibiotics-uk-aware-antibiotic-classification) categorises antibiotics into groups such as Access, Watch, and Reserve to guide healthcare professionals in optimising their use and mitigating antimicrobial resistance.

The existing list on the UKHSA site is not machine readable. To facilitate research, it is helpful to link this categorisation to the [dm+d standard](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/dictionary-medicines-and-devices-dmd).

### Imports
We need to import some libaries to help with the code

In [1]:
import pandas as pd
import requests
from ebmdatalab import bq
import os

### Getting the AWaRe list
The AWaRe list has been provided by the UKHSA team as an Excel spreadsheet. We can save the Excel spreadsheet as a CSV file then read into Pandas.

In [2]:
excel_path = os.path.join('..', 'data', 'AWaRe_UK_2024_translation_table_FINAL_UPDATED_20250429.xlsx')
df_ukhsa = pd.read_excel(excel_path)
df_ukhsa

,dmd,Antibiotic,Class,atccode,route,VmpUnit,WHO_AWaRe_2023,UK_AWaRe_2024,Include,Notes
0,Amikacin 100mg/2ml solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
1,Amikacin 1165mg/100ml solution for injection v...,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
2,Amikacin 1200mg solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
3,Amikacin 1300mg/50ml solution for injection vials,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
4,Amikacin 250mg/2ml injection,Amikacin,Aminoglycosides,J01GB06,P,ml,a,w,1,NaN
...,...,...,...,...,...,...,...,...,...,...
926,Vancomycin 50mg/5ml oral solution,Vancomycin_oral,Glycopeptides,A07AA09,O,ml,w,w,1,NaN
927,Vancomycin 5mg/0.5ml solution for injection pr...,Vancomycin_IV,Glycopeptides,J01XA01,P,ml,w,w,1,NaN
928,Vancomycin 62.5mg/5ml oral solution,Vancomycin_oral,Glycopeptides,A07AA09,O,ml,w,w,1,NaN
929,Vancomycin 750mg/250ml infusion bags,Vancomycin_IV,Glycopeptides,J01XA01,P,ml,w,w,1,NaN
930,Vancomycin 850mg powder for solution for infus...,Vancomycin_IV,Glycopeptides,J01XA01,P,vial,w,w,1,NaN

In [3]:
df_ukhsa_atccodes = df_ukhsa[['atccode', 'Antibiotic', 'WHO_AWaRe_2023', 'UK_AWaRe_2024']].drop_duplicates()
df_ukhsa_atccodes

with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_ukhsa_atccodes)

,atccode,Antibiotic,WHO_AWaRe_2023,UK_AWaRe_2024
0,J01GB06,Amikacin,a,w
10,J01CA04,Amoxicillin,a,a
24,J01CA01,Ampicillin,a,a
29,J01FA10,Azithromycin,w,w
35,J01DF51,Aztreonam/avibactam,r,r
36,J01DF01,Aztreonam,r,r
42,J04AK05,Bedaquiline,o,o
43,J01CE08,Benzathine-benzylpenicillin,a,a
49,J01CE01,Benzylpenicillin,a,a
55,J01CE02,Benzylpenicillin,a,a
57,J01CE00,Benzylpenicillin,a,a
58,J04AB30,Capreomycin,o,o
59,J01DC04,Cefaclor,w,w
66,J01DB05,Cefadroxil,a,a
70,J01DB01,Cefalexin,a,a
79,J01DB03,Cefalotin,a,a
80,J01DC03,Cefamandole,w,w
81,J01DB04,Cefazolin,a,a
84,J01DE01,Cefepime,w,w
86,J01DI04,Cefiderocol,r,r
87,J01DD08,Cefixime,w,w
90,J01DD01,Cefotaxime,w,w
93,J01DC01,Cefoxitin,w,w
95,J01DE02,Cefpirome,w,r
97,J01DD13,Cefpodoxime,w,w
99,J01DC10,Cefprozil,w,w
102,J01DB09,Cefradine,a,a
107,J01DI02,Ceftaroline-fosamil,r,r
108,J01DD02,Ceftazidime,w,w
127,J01DD52,Ceftazidime/avibactam,r,r
152,J01DI01,Ceftobiprole-medocaril,r,r
153,J01DI54,Ceftolozane/tazobactam,r,r
155,J01DD04,Ceftriaxone,w,w
163,J01DC02,Cefuroxime,w,w
183,J01BA01,Chloramphenicol,a,w
185,J01MA02,Ciprofloxacin,w,w
213,J01FA09,Clarithromycin,w,w
226,J01FF01,Clindamycin,a,w
248,J04BA01,Clofazimine,o,o
250,J01CR02,Amoxicillin/clavulanic-acid,a,w
265,J01CA51,Flucloxacillin/ampicillin,NR,o
268,J01XB01,Colistin_INH,r,r
270,J01XB01,Colistin_IV,r,r
279,A07AA10,Colistin_PO,r,r
282,A07AA10,Colistin_IV,r,r
286,J01EE01,Sulfamethoxazole/trimethoprim,a,a
293,J04AB01,Cycloserine,o,o
294,J01XA04,Dalbavancin,r,r
295,J01XX09,Daptomycin,r,r
297,J01MA23,Delafloxacin,w,w
299,J04AK06,Delamanid,o,o
300,J01AA01,Demeclocycline,w,o
311,J01DH04,Doripenem,w,r
312,J01AA02,Doxycycline,a,a
320,A01AB22,Doxycycline,a,a
325,J01AA13,Eravacycline,r,r
326,J01DH03,Ertapenem,w,r
327,J01FA01,Erythromycin,w,w
341,J04AK02,Ethambutol,o,o
367,A07AA12,Fidaxomicin,w,w
369,J01CF05,Flucloxacillin,a,a
396,J01XX01,Fosfomycin_IV,r,r
397,J01XX01,Fosfomycin_oral,w,a
404,J01XC01,Fusidic-acid,w,w
405,J01AA20,Chlortetracycline hydrochloride/demeclocycline hydrochloride/tetracycline hydrochloride,o,o
406,J01DH56,Imipenem/cilastatin/relebactam,r,r
407,J04AM06,Ethambutol hydrochloride/isoniazid/pyrazinamide/rifampicin,o,o
408,J01GB03,Gentamicin,a,a
433,J01DH51,Imipenem/cilastatin,w,r
437,J04AC01,Isoniazid,o,o
483,J01MA12,Levofloxacin,w,w
484,J01MA13,Levofloxacin,w,w
492,J01XX08,Linezolid,r,r
498,J01AA04,Lymecycline,w,w
499,J01DH02,Meropenem,w,r
500,J01DH52,Meropenem/vaborbactam,r,r
507,J01XX05,Methenamine,o,o
508,J01XD01,Metronidazole_IV,a,a
509,P01AB01,Metronidazole_oral,a,a
511,P01AB01,Metronidazole,a,a
524,J01AA08,Minocycline_oral,w,w
531,J01MA14,Moxifloxacin,w,w
540,J01MB02,Nalidixic Acid,o,o
543,A07AA01,Neomycin,w,w
546,J01GB05,Neomycin,w,w
547,J01GB07,Netilmicin,w,o
552,J01XE01,Nitrofurantoin,a,a
638,J01MA06,Norfloxacin,w,w
639,J01MA01,Ofloxacin,w,w
648,J01XA05,Oritavancin,r,r
649,J01AA06,Oxytetracycline,w,w
651,J01CR50,Penicillin combinations,NR,o
653,J01CE02,Phenoxymethylpenicillin,a,a
659,J01CA12,Piperacillin,w,w
660,J01CR05,Piperacillin/tazobactam,w,w
676,J01CA08,Pivmecillinam,a,a
678,J01FG01,Pristinamycin,w,o
680,J01CE09,Procaine-benzylpenicillin,a,a
684,J04AK01,Pyrazinamide,o,o
751,J01FG02,Dalfopristin/quinupristin,r,r
753,J04AB02,Rifampicin,w,o
754,J04AB02,Rifampicin/isoniazid/pyrazinamide,w,o
757,J04AB02,Rifampicin/isoniazid,w,o
778,J01FA06,Roxithromycin,w,o
781,J01XX04,Spectinomycin,a,o
782,J01FA02,Spiramycin,w,o
786,J01GA01,Streptomycin_IV,w,o
787,J01EC02,Sulfadiazine,a,o
792,J01ED05,Sulfamethoxypyridazine,a,o
793,J01EB04,Sulfapyridine,a,o
794,J01XX11,Tedizolid,r,r
796,J01XA02,Teicoplanin,w,w
806,J01XA03,Telavancin,r,r
808,J01FA15,Telithromycin,w,o
809,J01CA17,Temocillin,w,w
810,J01AA07,Tetracycline,a,a
813,J01CR03,Ticarcillin/clavulanic-acid,o,o
816,J01AA12,Tigecycline,r,r
820,P01AB02,Tinidazole,a,a
822,J01GB01,Tobramycin,w,w
876,J01EA01,Trimethoprim,a,a
889,J01XA01,Vancomycin_IV,w,w
898,A07AA09,Vancomycin_oral,w,w

In [4]:
# Construct the query using the formatted list.
sql = f"""
SELECT DISTINCT
  CAST (vmp.id AS string) AS vmp_id,
  vmp.nm AS vmp_nm,
  vmp.invalid AS invalid_vmp,
  CAST (vtm.id AS string) AS vtm_id,
  vtm.nm AS vtm_nm,
  COALESCE(sroute.route, routelookup.who_route) AS atc_route,
  atclookup.ATC AS atc
FROM `ebmdatalab.dmd.vmp` vmp
LEFT JOIN dmd.ont ont ON vmp.id = ont.vmp
LEFT JOIN dmd.vtm vtm ON vmp.vtm = vtm.id
LEFT JOIN dmd.ontformroute ofr ON ont.form = ofr.cd
LEFT JOIN `dmd.vpi_to_atc_march25` atclookup ON vmp.id = atclookup.VPID
LEFT JOIN chris.vmp_single_route_identifier sroute ON vmp.id = sroute.vmp_id -- this table maps VMP to a specific route where more than one is given
LEFT JOIN `scmd_dmd_views.dmd_to_atc_route` routelookup ON ofr.descr = routelookup.dmd_ofr  -- this table maps dmd route to ATC route
"""

# Define the CSV path for caching the results.
csv_path = os.path.join('..', 'data', 'vmp_vtms.csv')

# Use the cached_read function from the bq library to run the query.
vmp_vtms = bq.cached_read(sql, csv_path=csv_path)

# Force vmp_id and vtm_id to proper string type
vmp_vtms['vmp_id'] = vmp_vtms['vmp_id'].astype('string')
vmp_vtms['vtm_id'] = vmp_vtms['vtm_id'].astype('string')

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [5]:
vmp_vtms

,vmp_id,vmp_nm,invalid_vmp,vtm_id,vtm_nm,atc_route,atc
0,45010811000001105,Lazertinib 80mg tablets,False,44991411000001102,Lazertinib,O,None
1,44117211000001108,Generic DryMax Super dressing 5cm x 5cm square,False,<NA>,None,None,None
2,42801911000001108,Catheter safety valves,False,<NA>,None,None,None
3,41960011000001106,Copper coated barrier dressing sterile with ad...,False,<NA>,None,None,None
4,41535211000001108,Odevixibat 600microgram capsules,False,1179275005,Odevixibat,O,A05AX05
...,...,...,...,...,...,...,...
24698,43907811000001106,Somapacitan 10mg/1.5ml solution for injection ...,False,898161005,Somapacitan,P,H01AC07
24699,43907911000001101,Somapacitan 15mg/1.5ml solution for injection ...,False,898161005,Somapacitan,P,H01AC07
24700,44098211000001102,Budesonide 1mg/2ml nebuliser suspension unit d...,False,774924004,Budesonide,Inhal.solution,R03BA02
24701,43813811000001108,Generic PDE reach5 oral powder 18g sachets,False,<NA>,None,O,n/a
24702,43907711000001103,Generic Spikevax JN.1 COVID-19 mRNA Vaccine 50...,False,39330711000001103,COVID-19 vaccine,P,n/a

In [7]:
# Merge on ATC codes
df_ukhsa_atccodes_matched = (
    df_ukhsa_atccodes.merge(
        vmp_vtms,
        left_on='atccode',
        right_on='atc',
        how='left'
    )
)

with pd.option_context('display.max_rows', None):
    display(df_ukhsa_atccodes_matched)

,atccode,Antibiotic,WHO_AWaRe_2023,UK_AWaRe_2024,vmp_id,vmp_nm,invalid_vmp,vtm_id,vtm_nm,atc_route,atc
0,J01GB06,Amikacin,a,w,44422511000001103,Amikacin 500mg/2ml solution for injection ampo...,False,774534000,Amikacin,P,J01GB06
1,J01GB06,Amikacin,a,w,44007311000001107,Amikacin 25mg/5ml solution for injection ampoules,False,774534000,Amikacin,None,J01GB06
2,J01GB06,Amikacin,a,w,41823511000001108,Amikacin 500mg/100ml infusion polyethylene bot...,False,774534000,Amikacin,P,J01GB06
3,J01GB06,Amikacin,a,w,39601711000001109,Amikacin liposomal 590mg nebuliser dispersion ...,False,782421008,Amikacin liposomal,Inhal.solution,J01GB06
4,J01GB06,Amikacin,a,w,38244211000001108,Amikacin 400micrograms/0.1ml intravitreal inje...,False,774534000,Amikacin,None,J01GB06
5,J01GB06,Amikacin,a,w,35111911000001104,Amikacin 25mg/5ml solution for injection vials,False,774534000,Amikacin,None,J01GB06
6,J01GB06,Amikacin,a,w,35104511000001105,Amikacin 25mg/5ml solution for injection pre-f...,False,774534000,Amikacin,None,J01GB06
7,J01GB06,Amikacin,a,w,35899911000001109,Amikacin 500mg/2ml solution for injection vials,False,774534000,Amikacin,P,J01GB06
8,J01GB06,Amikacin,a,w,35899811000001104,Amikacin 100mg/2ml solution for injection vials,False,774534000,Amikacin,P,J01GB06
9,J01CA04,Amoxicillin,a,a,34226911000001109,Amoxicillin 500mg/50ml infusion bags,False,774586009,Amoxicillin,P,J01CA04
10,J01CA04,Amoxicillin,a,a,39732311000001104,Amoxicillin 250mg capsules,False,774586009,Amoxicillin,O,J01CA04
11,J01CA04,Amoxicillin,a,a,39732411000001106,Amoxicillin 500mg capsules,False,774586009,Amoxicillin,O,J01CA04
12,J01CA04,Amoxicillin,a,a,41941111000001109,Amoxicillin 250mg/5ml oral suspension,False,774586009,Amoxicillin,O,J01CA04
13,J01CA04,Amoxicillin,a,a,39021911000001105,Amoxicillin 250mg/5ml oral suspension sugar free,False,774586009,Amoxicillin,O,J01CA04
14,J01CA04,Amoxicillin,a,a,41940811000001105,Amoxicillin 125mg/5ml oral suspension,False,774586009,Amoxicillin,O,J01CA04
15,J01CA04,Amoxicillin,a,a,35901911000001104,Amoxicillin 125mg/5ml oral suspension sugar free,False,774586009,Amoxicillin,O,J01CA04
16,J01CA04,Amoxicillin,a,a,35368511000001109,Amoxicillin 125mg/1.25ml oral suspension paedi...,False,774586009,Amoxicillin,O,J01CA04
17,J01CA04,Amoxicillin,a,a,41941211000001103,Amoxicillin 500mg powder for solution for inje...,False,774586009,Amoxicillin,P,J01CA04
18,J01CA04,Amoxicillin,a,a,41941011000001108,Amoxicillin 250mg powder for solution for inje...,False,774586009,Amoxicillin,P,J01CA04
19,J01CA04,Amoxicillin,a,a,41940911000001100,Amoxicillin 1g powder for solution for injecti...,False,774586009,Amoxicillin,P,J01CA04
20,J01CA04,Amoxicillin,a,a,35902111000001107,Amoxicillin 3g oral powder sachets sugar free,False,774586009,Amoxicillin,O,J01CA04
21,J01CA04,Amoxicillin,a,a,44456411000001100,Amoxicillin 500mg tablets,False,774586009,Amoxicillin,O,J01CA04
22,J01CA04,Amoxicillin,a,a,38726811000001109,Amoxicillin 1g dispersible tablets sugar free,False,774586009,Amoxicillin,O,J01CA04
23,J01CA04,Amoxicillin,a,a,41941311000001106,Amoxicillin 500mg/5ml oral suspension sugar free,False,774586009,Amoxicillin,O,J01CA04
24,J01CA01,Ampicillin,a,a,41941511000001100,Ampicillin 250mg capsules,False,774590006,Ampicillin,O,J01CA01
25,J01CA01,Ampicillin,a,a,41941711000001105,Ampicillin 500mg capsules,False,774590006,Ampicillin,O,J01CA01
26,J01CA01,Ampicillin,a,a,41941411000001104,Ampicillin 125mg/5ml oral suspension,False,774590006,Ampicillin,O,J01CA01
27,J01CA01,Ampicillin,a,a,41941611000001101,Ampicillin 250mg/5ml oral suspension,False,774590006,Ampicillin,O,J01CA01
28,J01CA01,Ampicillin,a,a,41941811000001102,Ampicillin 500mg powder for solution for injec...,False,774590006,Ampicillin,P,J01CA01
29,J01CA01,Ampicillin,a,a,41941811000001102,Ampicillin 500mg powder for solution for injec...,False,774590006,Ampicillin,None,J01CA01
30,J01FA10,Azithromycin,w,w,41942111000001104,Azithromycin 500mg powder for solution for inf...,False,774722005,Azithromycin,P,J01FA10
31,J01FA10,Azithromycin,w,w,39733511000001103,Azithromycin 500mg tablets,False,774722005,Azithromycin,O,J01FA10
32,J01FA10,Azithromycin,w,w,41942011000001100,Azithromycin 250mg capsules,False,774722005,Azithromycin,O,J01FA10
33,J01FA10,Azithromycin,w,w,41941911000001107,Azithromycin 200mg/5ml oral suspension,False,774722005,Azithromycin,O,J01FA10
34,J01FA10,Azithromycin,w,w,11034311000001100,Azithromycin 250mg tablets,False,774722005,Azithromycin,O,J01FA10
35,J01FA10,Azithromycin,w,w,29668711000001101,Azithromycin 200mg/5ml oral suspension sugar free,False,774722005,Azithromycin,O,J01FA10
36,J01DF51,Aztreonam/avibactam,r,r,43801411000001109,Aztreonam 1.5g / Avibactam 500mg powder for so...,False,43796711000001109,Aztreonam + Avibactam,P,J01DF51
37,J01DF01,Aztreonam,r,r,41759611000001105,Aztreonam 500mg powder for solution for inject...,False,774725007,Aztreonam,P,J01DF01
38,J01DF01,Aztreonam,r,r,41759411000001107,Aztreonam 1g powder for solution for injection...,False,774725007,Aztreonam,P,J01DF01
39,J01DF01,Aztreonam,r,r,41759511000001106,Aztreonam 2g powder for solution for injection...,False,774725007,Aztreonam,P,J01DF01
40,J01DF01,Aztreonam,r,r,17463411000001109,Aztreonam 75mg powder and solvent for nebulise...,False,774725007,Aztreonam,Inhal.solution,J01DF01
41,J04AK05,Bedaquiline,o,o,44108211000001105,Bedaquiline 20mg tablets,False,774747007,Bedaquiline,O,J04AK05
42,J04AK05,Bedaquiline,o,o,24565811000001107,Bedaquiline 100mg tablets,False,774747007,Bedaquiline,O,J04AK05
43,J01CE08,Benzathine-benzylpenicillin,a,a,44168511000001109,Benzathine benzylpenicillin 2.4million unit po...,False,1234764000,Benzathine benzylpenicillin,P,J01CE08
44,J01CE08,Benzathine-benzylpenicillin,a,a,42683111000001104,Benzathine benzylpenicillin 1.2million unit po...,False,1234764000,Benzathine benzylpenicillin,P,J01CE08
45,J01CE08,Benzathine-benzylpenicillin,a,a,10153111000001102,Benzathine benzylpenicillin 1.2million unit po...,False,1234764000,Benzathine benzylpenicillin,P,J01CE08
46,J01CE08,Benzathine-benzylpenicillin,a,a,10153211000001108,Benzathine benzylpenicillin 2.4million unit po...,False,1234764000,Benzathine benzylpenicillin,P,J01CE08
47,J01CE08,Benzathine-benzylpenicillin,a,a,10150911000001107,"Benzathine benzylpenicillin 600,000unit powder...",False,1234764000,Benzathine benzylpenicillin,P,J01CE08
48,J01CE01,Benzylpenicillin,a,a,22097311000001100,Benzylpenicillin sodium 1.2g/50ml infusion bags,False,774826003,Benzylpenicillin,P,J01CE01
49,J01CE01,Benzylpenicillin,a,a,22085911000001105,Benzylpenicillin sodium 600mg/50ml infusion bags,False,774826003,Benzylpenicillin,P,J01CE01
50,J01CE01,Benzylpenicillin,a,a,41942311000001102,Benzylpenicillin sodium 600mg powder for solut...,False,774826003,Benzylpenicillin,P,J01CE01
51,J01CE01,Benzylpenicillin,a,a,41942211000001105,Benzylpenicillin sodium 1.2g powder for soluti...,False,774826003,Benzylpenicillin,P,J01CE01
52,J01CE02,Benzylpenicillin,a,a,41953811000001101,Phenoxymethylpenicillin 250mg tablets,False,777175009,Phenoxymethylpenicillin,O,J01CE02
53,J01CE02,Benzylpenicillin,a,a,41953911000001106,Phenoxymethylpenicillin 250mg/5ml oral solution,False,777175009,Phenoxymethylpenicillin,O,J01CE02
54,J01CE02,Benzylpenicillin,a,a,41953711000001109,Phenoxymethylpenicillin 125mg/5ml oral solution,False,777175009,Phenoxymethylpenicillin,O,J01CE02
55,J01CE02,Benzylpenicillin,a,a,44122111000001108,Phenoxymethylpenicillin 500mg tablets,False,777175009,Phenoxymethylpenicillin,O,J01CE02
56,J01CE02,Benzylpenicillin,a,a,9215111000001107,Phenoxymethylpenicillin 125mg/5ml oral solutio...,False,777175009,Phenoxymethylpenicillin,O,J01CE02
57,J01CE02,Benzylpenicillin,a,a,9215211000001101,Phenoxymethylpenicillin 250mg/5ml oral solutio...,False,777175009,Phenoxymethylpenicillin,O,J01CE02
58,J01CE00,Benzylpenicillin,a,a,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN
59,J04AB30,Capreomycin,o,o,41942411000001109,Capreomycin 1g powder for solution for injecti...,False,775035004,Capreomycin,P,J04AB30
60,J01DC04,Cefaclor,w,w,39735011000001107,Cefaclor 250mg capsules,False,775086009,Cefaclor,O,J01DC04
61,J01DC04,Cefaclor,w,w,39735111000001108,Cefaclor 500mg capsules,False,775086009,Cefaclor,O,J01DC04
62,J01DC04,Cefaclor,w,w,36134211000001100,Cefaclor 375mg modified-release tablets,False,775086009,Cefaclor,O,J01DC04
63,J01DC04,Cefaclor,w,w,36134011000001105,Cefaclor 125mg/5ml oral suspension sugar free,False,775086009,Cefaclor,O,J01DC04
64,J01DC04,Cefaclor,w,w,36134111000001106,Cefaclor 250mg/5ml oral suspension sugar free,False,775086009,Cefaclor,O,J01DC04
65,J01DC04,Cefaclor,w,w,41942611000001107,Cefaclor 250mg/5ml oral suspension,False,775086009,Cefaclor,O,J01DC04
66,J01DC04,Cefaclor,w,w,41942511000001108,Cefaclor 125mg/5ml oral suspension,False,775086009,Cefaclor,O,J01DC04
67,J01DB05,Cefadroxil,a,a,39735211000001102,Cefadroxil 500mg capsules,False,775087000,Cefadroxil,O,J01DB05
68,J01DB05,Cefadroxil,a,a,41942711000001103,Cefadroxil 125mg/5ml oral suspension,False,775087000,Cefadroxil,O,J01DB05
69,J01DB05,Cefadroxil,a,a,41942811000001106,Cefadroxil 250mg/5ml oral suspension,False,775087000,Cefadroxil,O,J01DB05
70,J01DB05,Cefadroxil,a,a,41942911000001101,Cefadroxil 500mg/5ml oral suspension,False,775087000,Cefadroxil,O,J01DB05
71,J01DB01,Cefalexin,a,a,41943111000001105,Cefalexin 250mg/5ml oral suspension,False,775088005,Cefalexin,O,J01DB01
72,J01DB01,Cefalexin,a,a,39735311000001105,Cefalexin 250mg capsules,False,775088005,Cefalexin,O,J01DB01
73,J01DB01,Cefalexin,a,a,41943011000001109,Cefalexin 125mg/5ml oral suspension,False,775088005,Cefalexin,O,J01DB01
74,J01DB01,Cefalexin,a,a,39694811000001102,Cefalexin 500mg capsules,False,775088005,Cefalexin,O,J01DB01
75,J01DB01,Cefalexin,a,a,39684111000001105,Cefalexin 250mg tablets,False,775088005,Cefalexin,O,J01DB01
76,J01DB01,Cefalexin,a,a,39735911000001106,Cefalexin 500mg tablets,False,775088005,Cefalexin,O,J01DB01
77,J01DB01,Cefalexin,a,a,36134311000001108,Cefalexin 500mg/5ml oral suspension,False,775088005,Cefalexin,O,J01DB01
78,J01DB01,Cefalexin,a,a,4515811000001108,Cefalexin 250mg/5ml oral suspension sugar free,False,775088005,Cefalexin,O,J01DB01
79,J01DB01,Cefalexin,a,a,4865011000001104,Cefalexin 125mg/5ml oral suspension sugar free,False,775088005,Cefalexin,O,J01DB01
80,J01DB03,Cefalotin,a,a,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN
81,J01DC03,Cefamandole,w,w,4457111000001107,Cefamandole 1g powder for solution for injecti...,False,775090006,Cefamandole,P,J01DC03
82,J01DB04,Cefazolin,a,a,41872611000001103,Cefazolin 1g powder for solution for injection...,False,775092003,Cefazolin,P,J01DB04
83,J01DB04,Cefazolin,a,a,41872711000001107,Cefazolin 500mg powder for solution for inject...,False,775092003,Cefazolin,P,J01DB04
84,J01DB04,Cefazolin,a,a,33631211000001106,Cefazolin 2g powder for solution for injection...,False,775092003,Cefazolin,P,J01DB04
85,J01DE01,Cefepime,w,w,36458411000001105,Cefepime 1g powder for solution for injection ...,False,775095001,Cefepime,P,J01DE01
86,J01DE01,Cefepime,w,w,36458511000001109,Cefepime 2g powder for solution for injection ...,False,775095001,Cefepime,P,J01DE01
87,J01DI04,Cefiderocol,r,r,39002611000001100,Cefiderocol 1g powder for solution for infusio...,False,830205006,Cefiderocol,P,J01DI04
88,J01DD08,Cefixime,w,w,41943211000001104,Cefixime 200mg tablets,False,775097009,Cefixime,O,J01DD08
89,J01DD08,Cefixime,w,w,36134411000001101,Cefixime 100mg/5ml oral suspension,False,775097009,Cefixime,O,J01DD08
90,J01DD08,Cefixime,w,w,41943311000001107,Cefixime 400mg tablets,False,775097009,Cefixime,O,J01DD08
91,J01DD01,Cefotaxime,w,w,44009011000001100,Cefotaxime 1g/50ml infusion bags,False,775103002,Cefotaxime,P,J01DD01
92,J01DD01,Cefotaxime,w,w,44007911000001108,Cefotaxime 2g/100ml infusion bags,False,775103002,Cefotaxime,P,J01DD01
93,J01DD01,Cefotaxime,w,w,41943411000001100,Cefotaxime 1g powder for solution for injectio...,False,775103002,Cefotaxime,P,J01DD01
94,J01DD01,Cefotaxime,w,w,41943511000001101,Cefotaxime 500mg powder for solution for injec...,False,775103002,Cefotaxime,P,J01DD01
95,J01DD01,Cefotaxime,w,w,4558311000001100,Cefotaxime 2g powder for solution for injectio...,False,775103002,Cefotaxime,P,J01DD01
96,J01DC01,Cefoxitin,w,w,41943611000001102,Cefoxitin 1g powder for solution for injection...,False,775107001,Cefoxitin,P,J01DC01
97,J01DC01,Cefoxitin,w,w,41943711000001106,Cefoxitin 2g powder for solution for injection...,False,775107001,Cefoxitin,P,J01DC01
98,J01DE02,Cefpirome,w,r,41943811000001103,Cefpirome 1g powder for solution for injection...,False,775108006,Cefpirome,P,J01DE02
99,J01DE02,Cefpirome,w,r,41943911000001108,Cefpirome 2g powder for solution for injection...,False,775108006,Cefpirome,P,J01DE02
100,J01DD13,Cefpodoxime,w,w,41944011000001106,Cefpodoxime 100mg tablets,False,775109003,Cefpodoxime,O,J01DD13
101,J01DD13,Cefpodoxime,w,w,35369711000001108,Cefpodoxime 40mg/5ml oral suspension,False,775109003,Cefpodoxime,O,J01DD13
102,J01DC10,Cefprozil,w,w,41944111000001107,Cefprozil 250mg tablets,False,775110008,Cefprozil,O,J01DC10
103,J01DC10,Cefprozil,w,w,41944311000001109,Cefprozil 500mg tablets,False,775110008,Cefprozil,O,J01DC10
104,J01DC10,Cefprozil,w,w,41944211000001101,Cefprozil 250mg/5ml oral suspension,False,775110008,Cefprozil,O,J01DC10
105,J01DB09,Cefradine,a,a,41944511000001103,Cefradine 250mg capsules,False,775112000,Cefradine,O,J01DB09
106,J01DB09,Cefradine,a,a,41944611000001104,Cefradine 500mg capsules,False,775112000,Cefradine,O,J01DB09
107,J01DB09,Cefradine,a,a,41944411000001102,Cefradine 1g powder for solution for injection...,False,775112000,Cefradine,P,J01DB09
108,J01DB09,Cefradine,a,a,41944711000001108,Cefradine 500mg powder for solution for inject...,False,775112000,Cefradine,P,J01DB09
109,J01DB09,Cefradine,a,a,36134511000001102,Cefradine 250mg/5ml oral solution,False,775112000,Cefradine,O,J01DB09
110,J01DI02,Ceftaroline-fosamil,r,r,21386911000001101,Ceftaroline fosamil 600mg powder for solution ...,False,21387311000001104,Ceftaroline fosamil,P,J01DI02
111,J01DD02,Ceftazidime,w,w,40558111000001101,Ceftazidime 2mg/0.1ml solution for injection p...,False,775115003,Ceftazidime,None,J01DD02
112,J01DD02,Ceftazidime,w,w,22455011000001109,Ceftazidime 1g/50ml solution for infusion pre-...,True,775115003,Ceftazidime,P,J01DD02
113,J01DD02,Ceftazidime,w,w,22097911000001104,Ceftazidime 1g/50ml infusion bags,False,775115003,Ceftazidime,P,J01DD02
114,J01DD02,Ceftazidime,w,w,22098511000001105,Ceftazidime 1g/25ml solution for infusion pre-...,False,775115003,Ceftazidime,P,J01DD02
115,J01DD02,Ceftazidime,w,w,323856006,Ceftazidime 2g intravenous infusion vials,True,775115003,Ceftazidime,P,J01DD02
116,J01DD02,Ceftazidime,w,w,41944811000001100,Ceftazidime 1g powder for solution for injecti...,False,775115003,Ceftazidime,P,J01DD02
117,J01DD02,Ceftazidime,w,w,41944911000001105,Ceftazidime 250mg powder for solution for inje...,False,775115003,Ceftazidime,P,J01DD02
118,J01DD02,Ceftazidime,w,w,41945211000001100,Ceftazidime 500mg powder for solution for inje...,False,775115003,Ceftazidime,P,J01DD02
119,J01DD02,Ceftazidime,w,w,41945011000001105,Ceftazidime 2g powder for solution for injecti...,False,775115003,Ceftazidime,P,J01DD02
120,J01DD02,Ceftazidime,w,w,41945111000001106,Ceftazidime 3g powder for solution for injecti...,False,775115003,Ceftazidime,P,J01DD02
121,J01DD52,Ceftazidime/avibactam,r,r,34179911000001103,Ceftazidime 2g / Avibactam 500mg powder for so...,False,781300005,Ceftazidime + Avibactam,P,J01DD52
122,J01DI01,Ceftobiprole-medocaril,r,r,31008911000001103,Ceftobiprole 500mg powder for solution for inf...,False,1287090001,Ceftobiprole,P,J01DI01
123,J01DI54,Ceftolozane/tazobactam,r,r,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN
124,J01DD04,Ceftriaxone,w,w,23107411000001109,Ceftriaxone 2g powder for solution for infusio...,True,775120003,Ceftriaxone,P,J01DD04
125,J01DD04,Ceftriaxone,w,w,22102411000001102,Ceftriaxone 1g/50ml infusion bags,False,775120003,Ceftriaxone,P,J01DD04
126,J01DD04,Ceftriaxone,w,w,41945311000001108,Ceftriaxone 1g powder for solution for injecti...,False,775120003,Ceftriaxone,P,J01DD04
127,J01DD04,Ceftriaxone,w,w,41945511000001102,Ceftriaxone 250mg powder for solution for inje...,False,775120003,Ceftriaxone,P,J01DD04
128,J01DD04,Ceftriaxone,w,w,41945611000001103,Ceftriaxone 2g powder for solution for injecti...,False,775120003,Ceftriaxone,P,J01DD04
129,J01DC02,Cefuroxime,w,w,30791311000001104,Cefuroxime 3mg/0.3ml solution for injection pr...,False,775121004,Cefuroxime,None,J01DC02
130,J01DC02,Cefuroxime,w,w,35893011000001107,Cefuroxime 1.5g/50ml infusion bags,False,775121004,Cefuroxime,P,J01DC02
131,J01DC02,Cefuroxime,w,w,35893111000001108,Cefuroxime 750mg/50ml infusion bags,False,775121004,Cefuroxime,P,J01DC02
132,J01DC02,Cefuroxime,w,w,23683311000001109,Cefuroxime 1.5g/100ml infusion bags,False,775121004,Cefuroxime,P,J01DC02
133,J01DC02,Cefuroxime,w,w,22104011000001100,Cefuroxime 300micrograms/0.3ml solution for in...,False,775121004,Cefuroxime,None,J01DC02
134,J01DC02,Cefuroxime,w,w,22041211000001105,Cefuroxime 1mg/0.1ml solution for injection pr...,False,775121004,Cefuroxime,None,J01DC02
135,J01DC02,Cefuroxime,w,w,21797311000001102,Cefuroxime 50mg powder for solution for inject...,False,775121004,Cefuroxime,None,J01DC02
136,J01DC02,Cefuroxime,w,w,41945811000001104,Cefuroxime 125mg/5ml oral suspension,False,775121004,Cefuroxime,O,J01DC02
137,J01DC02,Cefuroxime,w,w,39694611000001101,Cefuroxime 250mg tablets,False,775121004,Cefuroxime,O,J01DC02
138,J01DC02,Cefuroxime,w,w,39684511000001101,Cefuroxime 125mg tablets,False,775121004,Cefuroxime,O,J01DC02
139,J01DC02,Cefuroxime,w,w,41945711000001107,Cefuroxime 125mg granules for oral suspension ...,False,775121004,Cefuroxime,O,J01DC02
140,J01DC02,Cefuroxime,w,w,36134711000001107,Cefuroxime 750mg powder for solution for injec...,False,775121004,Cefuroxime,P,J01DC02
141,J01DC02,Cefuroxime,w,w,4557611000001106,Cefuroxime 1.5g powder for solution for inject...,False,775121004,Cefuroxime,P,J01DC02
142,J01DC02,Cefuroxime,w,w,41945911000001109,Cefuroxime 250mg powder for solution for injec...,False,775121004,Cefuroxime,P,J01DC02
143,J01BA01,Chloramphenicol,a,w,41946111000001100,Chloramphenicol 250mg capsules,False,775160002,Chloramphenicol,O,J01BA01
144,J01BA01,Chloramphenicol,a,w,41946011000001101,Chloramphenicol 1g powder for solution for inj...,False,775160002,Chloramphenicol,P,J01BA01
145,J01MA02,Ciprofloxacin,w,w,39686211000001109,Ciprofloxacin 100mg tablets,False,775261009,Ciprofloxacin,O,J01MA02
146,J01MA02,Ciprofloxacin,w,w,39687511000001109,Ciprofloxacin 250mg tablets,False,775261009,Ciprofloxacin,O,J01MA02
147,J01MA02,Ciprofloxacin,w,w,39687811000001107,Ciprofloxacin 500mg tablets,False,775261009,Ciprofloxacin,O,J01MA02
148,J01MA02,Ciprofloxacin,w,w,39687011000001101,Ciprofloxacin 750mg tablets,False,775261009,Ciprofloxacin,O,J01MA02
149,J01MA02,Ciprofloxacin,w,w,36141511000001100,Ciprofloxacin 400mg/200ml infusion bags,False,775261009,Ciprofloxacin,P,J01MA02
150,J01MA02,Ciprofloxacin,w,w,36141011000001108,Ciprofloxacin 200mg/100ml infusion bags,False,775261009,Ciprofloxacin,P,J01MA02
151,J01MA02,Ciprofloxacin,w,w,36140911000001100,Ciprofloxacin 100mg/50ml solution for infusion...,False,775261009,Ciprofloxacin,P,J01MA02
152,J01MA02,Ciprofloxacin,w,w,41760211000001107,Ciprofloxacin 250mg/5ml oral suspension,False,775261009,Ciprofloxacin,O,J01MA02
153,J01MA02,Ciprofloxacin,w,w,8967411000001108,Ciprofloxacin 200mg/100ml solution for infusio...,False,775261009,Ciprofloxacin,P,J01MA02
154,J01MA02,Ciprofloxacin,w,w,8973011000001101,Ciprofloxacin 400mg/200ml solution for infusio...,False,775261009,Ciprofloxacin,P,J01MA02
155,J01MA02,Ciprofloxacin,w,w,10892711000001106,Ciprofloxacin 100mg/50ml solution for infusion...,False,775261009,Ciprofloxacin,P,J01MA02
156,J01MA02,Ciprofloxacin,w,w,10892811000001103,Ciprofloxacin 200mg/100ml solution for infusio...,False,775261009,Ciprofloxacin,P,J01MA02
157,J01MA02,Ciprofloxacin,w,w,10892911000001108,Ciprofloxacin 400mg/200ml solution for infusio...,False,775261009,Ciprofloxacin,P,J01MA02

This gives us a large number of VMPs matched on ATC code. 

Manual review of the VMPs though shows a number of possible issues:
- J01CE02 - Used for some of the benzylpenicillin products but actually corresponds to phenoxymethylpenicillin
- J01CE00  - Used for some of the benzylpenicillin products but doesn't appear to be in use.
- J01DI54 - there is a relevent VMP but this doesn't have an ATC code allocated in the BSA VMP to ATC mapping.
- J01MA13 - used for levofloxacin but actually linked to 	trovafloxacin 
- J04AB02 - used for rifampicin/isoniazid/pyrazinamide combo - but actually relates only to rifampicin - correct code = J04AM05